import {json,admin} from '../_shared/utils.ts';
const enc=(s:string)=>btoa(unescape(encodeURIComponent(s)));
const ics=(l:any)=>{const start=new Date(l.starts_at),end=new Date(start.getTime()+l.duration_minutes*60000),fmt=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');return `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//AcmeLearn//IELTS//EN\r\nBEGIN:VEVENT\r\nUID:${l.id}@acmelearn\r\nDTSTAMP:${fmt(new Date())}\r\nDTSTART:${fmt(start)}\r\nDTEND:${fmt(end)}\r\nSUMMARY:${l.title}\r\nDESCRIPTION:Sign in to AcmeLearn. Your private Zoom link appears 15 minutes before class.\r\nURL:${Deno.env.get('SITE_URL')}/lectures.html\r\nEND:VEVENT\r\nEND:VCALENDAR`};
Deno.serve(async(req)=>{try{if(req.headers.get('x-cron-secret')!==Deno.env.get('CRON_SECRET'))return json({error:'Unauthorized'},401);
 const now=new Date().toISOString();const jobs=await admin(`/rest/v1/notifications?sent_at=is.null&scheduled_for=lte.${encodeURIComponent(now)}&select=*,lectures(*,courses(title))&limit=100`);let sent=0,failed=0;
 for(const job of jobs){try{const user=await admin(`/auth/v1/admin/users/${job.user_id}`),profiles=await admin(`/rest/v1/profiles?id=eq.${job.user_id}&select=*`),p=profiles[0],l=job.lectures;const when=new Intl.DateTimeFormat('en-NG',{dateStyle:'medium',timeStyle:'short',timeZone:p.timezone||'Africa/Lagos'}).format(new Date(l.starts_at));const message=`${l.title} starts ${job.kind==='15_minute'?'in 15 minutes':`on ${when}`}. Sign in to AcmeLearn for your private Zoom link.`;let provider_id='';
  if(job.channel==='email') {const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${Deno.env.get('RESEND_API_KEY')}`,'Content-Type':'application/json'},body:JSON.stringify({from:Deno.env.get('EMAIL_FROM'),to:[user.email],subject:`${job.kind==='15_minute'?'Starting soon':'Lecture reminder'}: ${l.title}`,html:`<h2>${l.title}</h2><p>${message}</p><p><a href="${Deno.env.get('SITE_URL')}/lectures.html">Open secure lecture room</a></p><p>Do not forward your meeting link.</p>`,attachments:[{filename:'acmelearn-lecture.ics',content:enc(ics(l))}]})});const b=await r.json();if(!r.ok)throw Error(b.message||'Email failed');provider_id=b.id}
  else {if(!p.whatsapp_opt_in||!p.phone){await admin(`/rest/v1/notifications?id=eq.${job.id}`,{method:'PATCH',body:JSON.stringify({sent_at:new Date().toISOString(),error:'Skipped: no WhatsApp consent/phone'})});continue}const sid=Deno.env.get('TWILIO_ACCOUNT_SID')!,auth=btoa(`${sid}:${Deno.env.get('TWILIO_AUTH_TOKEN')}`),contentSid=Deno.env.get('TWILIO_CONTENT_SID'),form=new URLSearchParams({From:Deno.env.get('TWILIO_WHATSAPP_FROM')!,To:`whatsapp:${p.phone}`});if(contentSid){form.set('ContentSid',contentSid);form.set('ContentVariables',JSON.stringify({'1':p.first_name||'Student','2':l.title,'3':when,'4':`${Deno.env.get('SITE_URL')}/lectures.html`}))}else form.set('Body',message+` ${Deno.env.get('SITE_URL')}/lectures.html`);const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`,{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},body:form});const b=await r.json();if(!r.ok)throw Error(b.message||'WhatsApp failed');provider_id=b.sid}
  await admin(`/rest/v1/notifications?id=eq.${job.id}`,{method:'PATCH',body:JSON.stringify({sent_at:new Date().toISOString(),provider_id,error:null})});sent++
 }catch(e){failed++;await admin(`/rest/v1/notifications?id=eq.${job.id}`,{method:'PATCH',body:JSON.stringify({error:e.message})})}}
 return json({processed:jobs.length,sent,failed});
}catch(e){return json({error:e.message},400)}});
