export const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Content-Type':'application/json'};
const url=Deno.env.get('SUPABASE_URL')!; const service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
export const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
export async function admin(path:string,init:RequestInit={}){const r=await fetch(url+path,{...init,headers:{apikey:service,Authorization:`Bearer ${service}`,'Content-Type':'application/json',...(init.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||b.msg||JSON.stringify(b));return b}
export async function authUser(req:Request){const jwt=req.headers.get('Authorization')?.replace('Bearer ','');if(!jwt)throw new Error('Authentication required');return admin('/auth/v1/user',{headers:{Authorization:`Bearer ${jwt}`}})}
export async function profile(id:string){const rows=await admin(`/rest/v1/profiles?id=eq.${id}&select=*`);if(!rows[0])throw new Error('Profile not found');return rows[0]}
export async function zoomToken(){const id=Deno.env.get('ZOOM_CLIENT_ID')!,secret=Deno.env.get('ZOOM_CLIENT_SECRET')!,account=Deno.env.get('ZOOM_ACCOUNT_ID')!;const r=await fetch(`https://zoom.us/oauth/token?grant_type=account_credentials&account_id=${account}`,{method:'POST',headers:{Authorization:`Basic ${btoa(`${id}:${secret}`)}`}});const b=await r.json();if(!r.ok)throw new Error(b.reason||'Zoom authentication failed');return b.access_token}
async function aesKey(){const raw=new TextEncoder().encode(Deno.env.get('LINK_ENCRYPTION_KEY')!);const digest=await crypto.subtle.digest('SHA-256',raw);return crypto.subtle.importKey('raw',digest,'AES-GCM',false,['encrypt','decrypt'])}
export async function encrypt(value:string){const iv=crypto.getRandomValues(new Uint8Array(12));const data=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await aesKey(),new TextEncoder().encode(value)));return `${btoa(String.fromCharCode(...iv))}.${btoa(String.fromCharCode(...data))}`}
export async function decrypt(value:string){const [a,b]=value.split('.');const iv=Uint8Array.from(atob(a),c=>c.charCodeAt(0)),data=Uint8Array.from(atob(b),c=>c.charCodeAt(0));const out=await crypto.subtle.decrypt({name:'AES-GCM',iv},await aesKey(),data);return new TextDecoder().decode(out)}
export async function rateLimit(key:string,limit:number,windowSeconds:number){const allowed=await admin('/rest/v1/rpc/check_rate_limit',{method:'POST',body:JSON.stringify({p_key:key,p_limit:limit,p_window_seconds:windowSeconds})});if(allowed!==true)throw new Error('Rate limit exceeded — please try again shortly.')}
export function clientIp(req:Request){return req.headers.get('x-forwarded-for')?.split(',')[0].trim()||'unknown'}
export async function callClaude(system:string,userMessage:string,maxTokens=1500):Promise<string>{const apiKey=Deno.env.get('ANTHROPIC_API_KEY');if(!apiKey)throw new Error('AI is not configured yet. Set ANTHROPIC_API_KEY as a Supabase secret.');const res=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'x-api-key':apiKey,'anthropic-version':'2023-06-01','content-type':'application/json'},body:JSON.stringify({model:'claude-sonnet-5',max_tokens:maxTokens,system,messages:[{role:'user',content:userMessage}]})});const completion=await res.json();if(!res.ok)throw new Error(completion.error?.message||'AI request failed');return completion.content?.[0]?.text??''}
export function parseJsonLoose(raw:string){const cleaned=raw.trim().replace(/^```(?:json)?/,'').replace(/```$/,'').trim();return JSON.parse(cleaned)}
// Shared by payment-webhook (live receipt) and replay-dead-letter (admin-triggered
// reprocessing of a previously-failed event) so there's one source of truth for
// what "a payment cleared" actually does.
export async function processPaymentReference(reference:string){const orders=await admin(`/rest/v1/orders?provider_reference=eq.${reference}&select=*,products(course_id,billing_type)`),o=orders[0];if(!o)throw new Error('Order not found');await admin(`/rest/v1/orders?id=eq.${o.id}`,{method:'PATCH',body:JSON.stringify({status:'paid',paid_at:new Date().toISOString()})});await admin('/rest/v1/invoices',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates'},body:JSON.stringify({order_id:o.id,invoice_number:`ACME-${new Date().getUTCFullYear()}-${String(Date.now()).slice(-8)}`})});const redemptions=await admin(`/rest/v1/coupon_redemptions?order_id=eq.${o.id}&select=coupon_id`);if(redemptions[0]){const cs=await admin(`/rest/v1/coupons?id=eq.${redemptions[0].coupon_id}&select=used_count`);await admin(`/rest/v1/coupons?id=eq.${redemptions[0].coupon_id}`,{method:'PATCH',body:JSON.stringify({used_count:(cs[0]?.used_count||0)+1})})}const referralsFlag=(await admin(`/rest/v1/feature_flags?flag=eq.referrals&select=enabled`))[0];const referral=referralsFlag?.enabled?(await admin(`/rest/v1/referrals?referred_user_id=eq.${o.user_id}&status=eq.signed_up&select=id&limit=1`))[0]:null;if(referral){const settings=await admin(`/rest/v1/platform_settings?key=eq.referral_reward_percent&select=value`),percent=Number(settings[0]?.value??10),reward=Math.round(o.amount_minor*percent/100);await admin(`/rest/v1/referrals?id=eq.${referral.id}`,{method:'PATCH',body:JSON.stringify({reward_minor:reward,status:'rewarded',order_id:o.id})})}if(o.products.course_id)await admin('/rest/v1/enrollments?on_conflict=user_id,course_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify({user_id:o.user_id,course_id:o.products.course_id,status:'active'})});await admin('/rest/v1/in_app_notifications',{method:'POST',body:JSON.stringify({user_id:o.user_id,title:'Payment confirmed',body:'Your course is active and ready to begin.',kind:'payment',action_url:'/index.html'})})}
