export const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Content-Type':'application/json'};
const url=Deno.env.get('SUPABASE_URL')!; const service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
export const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
export async function admin(path:string,init:RequestInit={}){const r=await fetch(url+path,{...init,headers:{apikey:service,Authorization:`Bearer ${service}`,'Content-Type':'application/json',...(init.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||b.msg||JSON.stringify(b));return b}
export async function authUser(req:Request){const jwt=req.headers.get('Authorization')?.replace('Bearer ','');if(!jwt)throw new Error('Authentication required');return admin('/auth/v1/user',{headers:{Authorization:`Bearer ${jwt}`}})}
export async function profile(id:string){const rows=await admin(`/rest/v1/profiles?id=eq.${id}&select=*`);if(!rows[0])throw new Error('Profile not found');return rows[0]}
export async function zoomToken(){const id=Deno.env.get('ZOOM_CLIENT_ID')!,secret=Deno.env.get('ZOOM_CLIENT_SECRET')!,account=Deno.env.get('ZOOM_ACCOUNT_ID')!;const r=await fetch(`https://zoom.us/oauth/token?grant_type=account_credentials&account_id=${account}`,{method:'POST',headers:{Authorization:`Basic ${btoa(`${id}:${secret}`)}`}});const b=await r.json();if(!r.ok)throw new Error(b.reason||'Zoom authentication failed');return b.access_token}
async function aesKey(){const raw=new TextEncoder().encode(Deno.env.get('LINK_ENCRYPTION_KEY')!);const digest=await crypto.subtle.digest('SHA-256',raw);return crypto.subtle.importKey('raw',digest,'AES-GCM',false,['encrypt','decrypt'])}
export async function encrypt(value:string){const iv=crypto.getRandomValues(new Uint8Array(12));const data=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await aesKey(),new TextEncoder().encode(value)));return `${btoa(String.fromCharCode(...iv))}.${btoa(String.fromCharCode(...data))}`}
export async function decrypt(value:string){const [a,b]=value.split('.');const iv=Uint8Array.from(atob(a),c=>c.charCodeAt(0)),data=Uint8Array.from(atob(b),c=>c.charCodeAt(0));const out=await crypto.subtle.decrypt({name:'AES-GCM',iv},await aesKey(),data);return new TextDecoder().decode(out)}
export async function rateLimit(key:string,limit:number,windowSeconds:number){const allowed=await admin('/rest/v1/rpc/check_rate_limit',{method:'POST',body:JSON.stringify({p_key:key,p_limit:limit,p_window_seconds:windowSeconds})});if(allowed!==true)throw new Error('Rate limit exceeded — please try again shortly.')}
export function clientIp(req:Request){return req.headers.get('x-forwarded-for')?.split(',')[0].trim()||'unknown'}
