const $=(s,p=document)=>p.querySelector(s); const $$=(s,p=document)=>[...p.querySelectorAll(s)];
if(window.AcmeCloud){AcmeCloud.captureOAuth();if(AcmeCloud.session()&&!localStorage.getItem('acmeProfile'))AcmeCloud.me().then(async u=>{if(!u)return;let p={};try{p=(await AcmeCloud.table('profiles',`id=eq.${u.id}&select=*`))[0]||{}}catch{}localStorage.setItem('acmeProfile',JSON.stringify({id:u.id,email:u.email,firstName:p.first_name||u.user_metadata?.first_name||'Student',role:p.role||'student'}));location.reload()})}
const profile=JSON.parse(localStorage.getItem('acmeProfile')||localStorage.getItem('bandupProfile')||'null');
if(profile&&!localStorage.getItem('acmeProfile')) localStorage.setItem('acmeProfile',JSON.stringify(profile));
const isSignedIn=!!profile;
if(window.AcmeCloud?.demoMode()){const ribbon=document.createElement('div');ribbon.className='demo-ribbon';ribbon.textContent='Illustrative demo data';document.body.append(ribbon)}

// Five primary student destinations; advanced tools live inside Learn and Account.
$$('.navlinks').forEach(nav=>{
  const file=location.pathname.split('/').pop()||'index.html';
  if(isSignedIn&&profile.role==='student'){
    const links=[['index.html','Dashboard'],['learning.html','Learn'],['assignments.html','Assignments'],['lectures.html','Live classes'],['account.html','Account']];
    nav.innerHTML=links.map(([href,label])=>`<a class="${file===href?'active':''}" href="${href}">${label}</a>`).join('');
  }else{
    if(!$('.home-link',nav)){const a=document.createElement('a');a.className='home-link';a.href='index.html';a.textContent=isSignedIn?'Dashboard':'Home';nav.prepend(a)}
    if(isSignedIn&&['admin','tutor'].includes(profile.role)&&!$('.staff-link',nav)){const a=document.createElement('a');a.className='staff-link';a.href=profile.role==='admin'?'admin.html':'tutor.html';a.textContent=profile.role==='admin'?'Admin':'Tutor area';nav.append(a)}
  }
});
$$('.toplinks a').forEach(a=>{if(/student login/i.test(a.textContent)&&isSignedIn){a.textContent='My dashboard';a.href='index.html'}});
$$('.nav-actions').forEach(actions=>{
  if(isSignedIn){actions.innerHTML=`<button class="account-chip global-search" aria-label="Search AcmeLearn" style="border:0;background:none">⌕ Search</button><a class="account-chip" href="notifications.html" aria-label="Notifications">● <span style="position:absolute;width:7px;height:7px;background:var(--coral);border-radius:50%"></span></a><a class="account-chip" href="account.html"><span class="avatar">${(profile.firstName||'S')[0].toUpperCase()}</span>${profile.firstName||'Student'}</a><button class="btn btn-outline signout">Sign out</button>`}
});
$$('.signout').forEach(b=>b.addEventListener('click',async()=>{if(window.AcmeCloud)await AcmeCloud.logout();localStorage.removeItem('acmeProfile');localStorage.removeItem('bandupProfile');location.href='index.html'}));

const landing=$('#landing'), dashboard=$('#dashboard');
if(landing&&dashboard){landing.style.display=isSignedIn?'none':'block';dashboard.style.display=isSignedIn?'block':'none';if(isSignedIn){$('#studentName').textContent=profile.firstName||'Learner';document.title='Dashboard — AcmeLearn'}}
const date=$('#dashDate');if(date)date.textContent=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());
const floatCta=$('#diagnosticFloat');if(floatCta&&isSignedIn)floatCta.classList.add('hidden');
const state=$('#stateBanner');if(state&&isSignedIn){const diag=JSON.parse(localStorage.getItem('acmeDiagnostic')||'null'),exam=profile.examDate?Math.ceil((new Date(profile.examDate)-new Date())/86400000):null,last=Number(localStorage.getItem('acmeLastActive')||Date.now()),inactive=(Date.now()-last)>7*86400000;if(profile.completed)state.innerHTML='<span><strong>Course completed—keep your skills active.</strong><small style="display:block">Review recordings or download your completion certificate.</small></span><a class="btn btn-dark" href="certificate.html">View certificate →</a>';else if(!diag)state.innerHTML='<span><strong>Welcome to AcmeLearn.</strong><small style="display:block">Complete the short diagnostic to personalize your dashboard.</small></span><a class="btn btn-dark" href="learning.html">Start diagnostic →</a>';else if(exam!==null&&exam<=14)state.innerHTML=`<span><strong>${Math.max(0,exam)} days until your exam.</strong><small style="display:block">Switch to final-review mode with timed mocks and focused correction.</small></span><a class="btn btn-dark" href="mock.html">Start timed mock →</a>`;else if(inactive)state.innerHTML='<span><strong>Welcome back—restart with one short activity.</strong><small style="display:block">Your progress is saved. A 12-minute drill is ready.</small></span><a class="btn btn-dark" href="practice.html">Resume →</a>';else state.innerHTML='<span><strong>Your plan is on track.</strong><small style="display:block">Today’s highest-impact activity is ready.</small></span><a class="btn btn-dark" href="writing.html">Continue plan →</a>';localStorage.setItem('acmeLastActive',String(Date.now()))}

// Protected lecture area. In production this is backed by server-side session checks.
if(document.body.dataset.protected==='true'&&!isSignedIn){sessionStorage.setItem('acmeReturnTo',location.pathname.split('/').pop()||'lectures.html');location.replace('login.html?required=1')}
if(document.body.dataset.role&&isSignedIn){const allowed=document.body.dataset.role.split(',');if(!allowed.includes(profile.role)){document.body.innerHTML='<main class="page-hero"><div class="shell"><span class="eyebrow">Access restricted</span><h1>Staff access only.</h1><p>Your account does not have permission to view this area.</p><a class="btn btn-dark" href="index.html">Return to dashboard</a></div></main>'}}

function completeAuth(firstName,email,provider='email',extra={}){
  const role=(email||'').toLowerCase().startsWith('admin@')?'admin':(email||'').toLowerCase().startsWith('tutor@')?'tutor':'student';
  localStorage.setItem('acmeProfile',JSON.stringify({firstName:firstName||'Student',email:email||`${provider}@acmelearn.student`,provider,target:'7.0',role,...extra}));
  const next=sessionStorage.getItem('acmeReturnTo')||'index.html';sessionStorage.removeItem('acmeReturnTo');location.href=next;
}
const signup=$('#signupForm');if(signup)signup.addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(signup),btn=$('.submit');btn.textContent='Creating your plan…';try{if(window.AcmeCloud&&!AcmeCloud.demoMode()){const s=await AcmeCloud.signUp(d.get('email'),d.get('password'),{first_name:d.get('firstName'),last_name:d.get('lastName'),target_band:d.get('target'),phone:d.get('phone'),whatsapp_opt_in:d.get('whatsapp_opt_in')==='on'});if(s.access_token){let p={};try{p=(await AcmeCloud.table('profiles',`id=eq.${s.user.id}&select=*`))[0]||{}}catch{}localStorage.setItem('acmeProfile',JSON.stringify({id:s.user.id,email:s.user.email,firstName:p.first_name||d.get('firstName'),role:p.role||'student',examDate:d.get('date')}));location.href='index.html'}else{btn.textContent='Check your email to continue';toast('We sent you a secure confirmation link.')}}else setTimeout(()=>completeAuth(d.get('firstName'),d.get('email'),'email',{examDate:d.get('date')}),450)}catch(err){btn.textContent='Create my free plan →';toast(err.message)}});
const login=$('#loginForm');if(login)login.addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(login),guessed=(d.get('email')||'Student').split('@')[0].split(/[._-]/)[0],name=guessed.charAt(0).toUpperCase()+guessed.slice(1),btn=$('.submit');btn.textContent='Signing you in…';try{if(window.AcmeCloud&&!AcmeCloud.demoMode()){const s=await AcmeCloud.signIn(d.get('email'),d.get('password'));let p={};try{p=(await AcmeCloud.table('profiles',`id=eq.${s.user.id}&select=*`))[0]||{}}catch{}localStorage.setItem('acmeProfile',JSON.stringify({id:s.user.id,email:s.user.email,firstName:p.first_name||name,role:p.role||'student'}));location.href=sessionStorage.getItem('acmeReturnTo')||'index.html'}else setTimeout(()=>completeAuth(name,d.get('email'),'email'),350)}catch(err){btn.textContent='Sign in →';toast(err.message)}});
$$('[data-provider]').forEach(btn=>btn.addEventListener('click',()=>{btn.textContent='Connecting…';if(window.AcmeCloud&&!AcmeCloud.demoMode())AcmeCloud.oauth(btn.dataset.provider);else setTimeout(()=>completeAuth('Student','',btn.dataset.provider),350)}));
if(new URLSearchParams(location.search).has('required')){const notice=$('#loginNotice');if(notice)notice.classList.remove('hidden')}

function toast(message){const t=$('#toast');if(!t)return;t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
$$('.practice-start').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();toast(isSignedIn?'Practice added to your study plan':'Create a free account to save this activity')}));
$$('.join-session').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();if(!isSignedIn){location.href='login.html?required=1';return}toast(`Opening secure ${b.dataset.platform} classroom…`)}));
$$('.pill').forEach(p=>p.addEventListener('click',()=>{const parent=p.parentElement;$$('.pill',parent).forEach(x=>x.classList.remove('active'));p.classList.add('active');const filter=p.dataset.filter;$$('[data-skill]').forEach(card=>card.style.display=(!filter||filter==='all'||card.dataset.skill===filter)?'block':'none')}));
const searchIndex=[['Writing workspace','Create and submit IELTS essays','writing.html'],['Speaking simulator','Record a private speaking response','speaking.html'],['Mock exam','Timed four-skill practice','mock.html'],['Assignments','Deadlines, submissions and feedback','assignments.html'],['Live classes','Secure Zoom lectures','lectures.html'],['Recordings','Your enrolled lecture recordings','recordings.html'],['Exam readiness','Practice-level forecast','readiness.html'],['Receipts','Invoices and payment history','receipts.html'],['Support','Help articles and tickets','support.html'],['Account security','MFA, password and devices','security.html'],['Privacy controls','Export or delete your data','privacy.html']];
$$('.global-search').forEach(b=>b.addEventListener('click',()=>{const wrap=document.createElement('div');wrap.className='search-overlay';wrap.innerHTML='<div class="search-dialog" role="dialog" aria-modal="true" aria-label="Search AcmeLearn"><div style="display:flex;gap:10px"><input class="search-input" autofocus placeholder="Search lessons, feedback, help…" aria-label="Search"><button class="btn btn-outline search-close">Close</button></div><div class="search-results"></div></div>';document.body.append(wrap);const input=$('.search-input',wrap),results=$('.search-results',wrap);const draw=q=>{const found=searchIndex.filter(x=>(x[0]+' '+x[1]).toLowerCase().includes(q.toLowerCase()));results.innerHTML=found.map(x=>`<a class="search-result" href="${x[2]}"><b>${x[0]}</b><small>${x[1]}</small></a>`).join('')||'<p>No matching content found.</p>'};draw('');input.addEventListener('input',()=>draw(input.value));input.focus();$('.search-close',wrap).onclick=()=>wrap.remove();wrap.addEventListener('click',e=>{if(e.target===wrap)wrap.remove()})}));
const menu=$('.mobile-menu');if(menu)menu.addEventListener('click',()=>{const links=$('.navlinks');links.style.display=links.style.display==='flex'?'none':'flex';Object.assign(links.style,{position:'absolute',top:'82px',left:'0',right:'0',background:'#fff',padding:'25px',flexDirection:'column',boxShadow:'0 15px 30px rgba(0,0,0,.1)'})});