(()=>{const $=(s,p=document)=>p.querySelector(s),cloud=window.AcmeCloud;const toast=m=>{const t=$('#toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}};const profile=()=>JSON.parse(localStorage.getItem('acmeProfile')||'null');async function rest(table,body,method='POST',query=''){if(cloud.demoMode())return body;const r=await fetch(`${ACME_CONFIG.SUPABASE_URL}/rest/v1/${table}${query}`,{method,headers:{apikey:ACME_CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${cloud.session().access_token}`,'Content-Type':'application/json',Prefer:'return=representation,resolution=merge-duplicates'},body:body?JSON.stringify(body):undefined});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.message||'Request failed');return b}
$('#bookCoaching')?.addEventListener('click',async()=>{const slot=$('input[name=slot]:checked');if(!slot)return toast('Choose an available time first.');if(!profile())return location.href='login.html?required=1';try{const out=cloud.demoMode()?{expires_in:900}:await cloud.invoke('book-coaching',{starts_at:slot.value,duration_minutes:50});toast('Slot reserved for 15 minutes. Continue to secure payment.');setTimeout(()=>location.href='billing.html',700)}catch(e){toast(e.message)}});
$('#blockTimeForm')?.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));d.tutor_id=profile()?.id;d.starts_at=new Date(d.starts_at).toISOString();d.ends_at=new Date(d.ends_at).toISOString();try{await rest('tutor_blocks',d);toast('Calendar block added and booking availability updated.');e.currentTarget.reset()}catch(err){toast(err.message)}});
$('#classChange')?.addEventListener('click',()=>toast('Class-change workflow opened: choose reschedule, self-study replacement or service credit.'));
$('#questionForm')?.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));d.prompt={text:d.prompt};d.answer={text:d.answer};d.difficulty=Number(d.difficulty);d.created_by=profile()?.id;d.status='draft';try{await rest('question_items',d);toast('Question saved as a draft for independent review.');e.currentTarget.reset()}catch(err){toast(err.message)}});
$('#couponForm')?.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));d.code=d.code.toUpperCase();d.discount_value=Number(d.discount_value);d.max_uses=d.max_uses?Number(d.max_uses):null;d.ends_at=d.ends_at?new Date(d.ends_at).toISOString():null;try{await rest('coupons',d);toast('Coupon created with an audit record.');e.currentTarget.reset()}catch(err){toast(err.message)}});
$('#scholarshipForm')?.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));d.user_id=profile()?.id;try{await rest('scholarship_applications',d);toast('Scholarship application submitted for review.');e.currentTarget.reset()}catch(err){toast(err.message)}});
$('#refundForm')?.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));try{if(cloud.demoMode()){await new Promise(r=>setTimeout(r,400));toast('Demo refund request queued.')}else{await cloud.invoke('request-refund',d);toast('Refund request submitted for eligibility review.')}e.currentTarget.reset()}catch(err){toast(err.message)}});
$('#refreshReadiness')?.addEventListener('click',async e=>{const b=e.currentTarget;b.textContent='Calculating…';try{if(cloud.demoMode()){await new Promise(r=>setTimeout(r,500));$('#readinessProbability').textContent='74%'}else{const out=await cloud.invoke('calculate-readiness',{});$('#readinessProbability').textContent=`${Math.round(out.probability*100)}%`}toast('Forecast updated from your latest four-skill evidence.')}catch(err){toast(err.message)}finally{b.textContent='Recalculate forecast →'}});
let factorId,challengeId;$('#enrolMfa')?.addEventListener('click',async()=>{if(cloud.demoMode()){factorId='demo';challengeId='demo';$('#mfaQr').textContent='Demo setup key: ACME LEARN DEMO';$('#mfaSetup').classList.remove('hidden');return}try{const token=cloud.session().access_token,r=await fetch(`${ACME_CONFIG.SUPABASE_URL}/auth/v1/factors`,{method:'POST',headers:{apikey:ACME_CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({factor_type:'totp',friendly_name:'AcmeLearn authenticator'})}),f=await r.json();if(!r.ok)throw Error(f.message);factorId=f.id;$('#mfaQr').innerHTML=f.totp?.qr_code||`Secret: ${f.totp?.secret}`;const c=await fetch(`${ACME_CONFIG.SUPABASE_URL}/auth/v1/factors/${factorId}/challenge`,{method:'POST',headers:{apikey:ACME_CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${token}`}}),ch=await c.json();challengeId=ch.id;$('#mfaSetup').classList.remove('hidden')}catch(e){toast(e.message)}});
$('#verifyMfa')?.addEventListener('click',async()=>{const code=$('#mfaCode').value;if(code.length!==6)return toast('Enter the six-digit authenticator code.');if(!cloud.demoMode())try{const token=cloud.session().access_token,r=await fetch(`${ACME_CONFIG.SUPABASE_URL}/auth/v1/factors/${factorId}/verify`,{method:'POST',headers:{apikey:ACME_CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({challenge_id:challengeId,code})});if(!r.ok)throw Error((await r.json()).message)}catch(e){return toast(e.message)}$('#mfaStatus').textContent='Enabled';$('#mfaStatus').classList.remove('warn');$('#mfaSetup').classList.add('hidden');toast('Multi-factor authentication enabled. Store recovery codes safely.')});
$('#signOutAll')?.addEventListener('click',async()=>{try{if(!cloud.demoMode())await fetch(`${ACME_CONFIG.SUPABASE_URL}/auth/v1/logout?scope=global`,{method:'POST',headers:{apikey:ACME_CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${cloud.session().access_token}`}});await cloud.logout();location.href='login.html'}catch(e){toast(e.message)}});
$('#recoveryForm')?.addEventListener('submit',async e=>{e.preventDefault();const email=new FormData(e.currentTarget).get('email');try{if(!cloud.demoMode()){const r=await fetch(`${ACME_CONFIG.SUPABASE_URL}/auth/v1/recover`,{method:'POST',headers:{apikey:ACME_CONFIG.SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,redirect_to:`${location.origin}/reset-password.html`})});if(!r.ok)throw Error((await r.json()).message)}toast('If that account exists, a reset link has been sent.')}catch(err){toast(err.message)}});$('#newPasswordForm')?.addEventListener('submit',async e=>{e.preventDefault();const password=new FormData(e.currentTarget).get('password');try{if(!cloud.demoMode()){const r=await fetch(`${ACME_CONFIG.SUPABASE_URL}/auth/v1/user`,{method:'PUT',headers:{apikey:ACME_CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${cloud.session().access_token}`,'Content-Type':'application/json'},body:JSON.stringify({password})});if(!r.ok)throw Error((await r.json()).message)}$('#resetComplete').classList.remove('hidden');e.currentTarget.reset()}catch(err){toast(err.message)}});
$('#replayWebhook')?.addEventListener('click',()=>toast('Select a dead-letter event before replay. Every replay is audited.'));
})();