-- AcmeLearn controlled-launch operations. Run after phase_extensions.sql.
create extension if not exists btree_gist;

create table public.platform_settings(key text primary key,value jsonb not null,updated_by uuid references profiles,updated_at timestamptz default now());
create table public.tutor_availability(id uuid primary key default gen_random_uuid(),tutor_id uuid references profiles on delete cascade,weekday int check(weekday between 0 and 6),starts_at time not null,ends_at time not null,timezone text default 'Africa/Lagos',effective_from date,effective_until date,unique(tutor_id,weekday,starts_at));
create table public.tutor_blocks(id uuid primary key default gen_random_uuid(),tutor_id uuid references profiles on delete cascade,starts_at timestamptz not null,ends_at timestamptz not null,reason text,created_at timestamptz default now(),check(ends_at>starts_at));
create table public.coaching_bookings(id uuid primary key default gen_random_uuid(),student_id uuid references profiles on delete cascade,tutor_id uuid references profiles on delete cascade,starts_at timestamptz not null,ends_at timestamptz not null,status text default 'pending' check(status in ('pending','confirmed','completed','cancelled','no_show')),order_id uuid references orders,zoom_meeting_id text,created_at timestamptz default now(),check(ends_at>starts_at));
alter table coaching_bookings add constraint no_tutor_booking_overlap exclude using gist(tutor_id with =,tstzrange(starts_at,ends_at,'[)') with &&) where(status in ('pending','confirmed'));
create table public.cohorts(id uuid primary key default gen_random_uuid(),course_id uuid references courses on delete cascade,name text not null,tutor_id uuid references profiles,max_students int default 25,start_date date,end_date date,status text default 'open');
create table public.cohort_members(id uuid primary key default gen_random_uuid(),cohort_id uuid references cohorts on delete cascade,user_id uuid references profiles on delete cascade,status text default 'active',unique(cohort_id,user_id));
create table public.waitlist_entries(id uuid primary key default gen_random_uuid(),user_id uuid references profiles on delete cascade,course_id uuid references courses on delete cascade,cohort_id uuid references cohorts on delete cascade,position int,status text default 'waiting',created_at timestamptz default now(),unique(user_id,course_id,status));
create table public.class_changes(id uuid primary key default gen_random_uuid(),lecture_id uuid references lectures on delete cascade,kind text check(kind in ('cancelled','rescheduled','substitute','self_study')),reason text,new_starts_at timestamptz,service_credit_minor int default 0,notified_at timestamptz,created_by uuid references profiles,created_at timestamptz default now());

create table public.question_items(id uuid primary key default gen_random_uuid(),skill text not null,question_type text,prompt jsonb not null,answer jsonb not null,explanation text,difficulty numeric(3,2) check(difficulty between 0 and 1),license_source text,license_expires_at date,status text default 'draft',version int default 1,created_by uuid references profiles,reviewed_by uuid references profiles,created_at timestamptz default now());
create table public.assessment_versions(id uuid primary key default gen_random_uuid(),title text not null,exam_type text default 'academic',version int not null,status text default 'draft',time_limit_minutes int,created_at timestamptz default now(),unique(title,version));
create table public.assessment_items(assessment_id uuid references assessment_versions on delete cascade,question_id uuid references question_items,position int not null,primary key(assessment_id,question_id));
create table public.marking_moderations(id uuid primary key default gen_random_uuid(),submission_id uuid references writing_submissions on delete cascade,original_marker uuid references profiles,moderator_id uuid references profiles,original_score numeric(2,1),moderated_score numeric(2,1),criterion_differences jsonb,notes text,status text default 'pending',created_at timestamptz default now());
create table public.score_review_requests(id uuid primary key default gen_random_uuid(),submission_id uuid references writing_submissions on delete cascade,user_id uuid references profiles,reason text,status text default 'requested',resolution text,reviewed_by uuid references profiles,created_at timestamptz default now(),unique(submission_id,user_id));
create table public.speaking_comments(id uuid primary key default gen_random_uuid(),attempt_id uuid references speaking_attempts on delete cascade,author_id uuid references profiles,timestamp_seconds numeric,comment text not null,created_at timestamptz default now());
create table public.readiness_forecasts(id uuid primary key default gen_random_uuid(),user_id uuid references profiles on delete cascade,target_band numeric(2,1),probability numeric(4,3),lower_band numeric(2,1),upper_band numeric(2,1),factors jsonb,disclaimer text default 'Forecast only; not a guarantee of an official IELTS result.',calculated_at timestamptz default now());

create table public.coupons(id uuid primary key default gen_random_uuid(),code text unique not null,discount_type text check(discount_type in ('percent','fixed')),discount_value int not null,currency text,max_uses int,used_count int default 0,starts_at timestamptz,ends_at timestamptz,course_id uuid references courses,active boolean default true);
create table public.coupon_redemptions(id uuid primary key default gen_random_uuid(),coupon_id uuid references coupons,user_id uuid references profiles,order_id uuid references orders,discount_minor int not null,created_at timestamptz default now(),unique(coupon_id,user_id));
create table public.scholarship_applications(id uuid primary key default gen_random_uuid(),user_id uuid references profiles,course_id uuid references courses,statement text,status text default 'submitted',discount_percent int,reviewed_by uuid references profiles,created_at timestamptz default now());
create table public.invoices(id uuid primary key default gen_random_uuid(),order_id uuid unique references orders on delete cascade,invoice_number text unique not null,billing_name text,billing_address text,tax_minor int default 0,issued_at timestamptz default now());
create table public.refunds(id uuid primary key default gen_random_uuid(),order_id uuid references orders,amount_minor int,reason text,status text default 'requested',provider_refund_id text,requested_by uuid references profiles,reviewed_by uuid references profiles,created_at timestamptz default now(),processed_at timestamptz);
create table public.referrals(id uuid primary key default gen_random_uuid(),referrer_id uuid references profiles,code text unique not null,referred_user_id uuid references profiles,reward_minor int default 0,status text default 'clicked',order_id uuid references orders,created_at timestamptz default now());

create table public.webhook_jobs(id bigint generated always as identity primary key,provider text,event_id text unique,event_type text,payload jsonb,status text default 'queued',attempts int default 0,next_attempt_at timestamptz default now(),last_error text,created_at timestamptz default now(),processed_at timestamptz);
create table public.webhook_dead_letters(id bigint generated always as identity primary key,job_id bigint,provider text,event_id text,payload jsonb,error text,failed_at timestamptz default now(),replayed_by uuid references profiles,replayed_at timestamptz);
create table public.service_incidents(id uuid primary key default gen_random_uuid(),service text,severity text,status text default 'investigating',title text,details text,started_at timestamptz default now(),resolved_at timestamptz,created_by uuid references profiles);
create table public.rate_limits(key text primary key,count int default 1,window_started_at timestamptz default now());

create or replace function public.consume_rate_limit(rate_key text,max_count int,window_seconds int) returns boolean language plpgsql security definer set search_path=public as $$
declare allowed boolean;
begin insert into rate_limits(key,count,window_started_at) values(rate_key,1,now()) on conflict(key) do update set count=case when rate_limits.window_started_at<now()-make_interval(secs=>window_seconds) then 1 else rate_limits.count+1 end,window_started_at=case when rate_limits.window_started_at<now()-make_interval(secs=>window_seconds) then now() else rate_limits.window_started_at end returning count<=max_count into allowed;return allowed;end$$;
revoke all on function public.consume_rate_limit(text,int,int) from public,anon,authenticated;grant execute on function public.consume_rate_limit(text,int,int) to service_role;

-- Row-level security
alter table platform_settings enable row level security;alter table tutor_availability enable row level security;alter table tutor_blocks enable row level security;alter table coaching_bookings enable row level security;alter table cohorts enable row level security;alter table cohort_members enable row level security;alter table waitlist_entries enable row level security;alter table class_changes enable row level security;alter table question_items enable row level security;alter table assessment_versions enable row level security;alter table assessment_items enable row level security;alter table marking_moderations enable row level security;alter table score_review_requests enable row level security;alter table speaking_comments enable row level security;alter table readiness_forecasts enable row level security;alter table coupons enable row level security;alter table coupon_redemptions enable row level security;alter table scholarship_applications enable row level security;alter table invoices enable row level security;alter table refunds enable row level security;alter table referrals enable row level security;alter table webhook_jobs enable row level security;alter table webhook_dead_letters enable row level security;alter table service_incidents enable row level security;alter table rate_limits enable row level security;
create policy "settings admin" on platform_settings for all using(acme_role()='admin') with check(acme_role()='admin');
create policy "availability public read" on tutor_availability for select using(true);create policy "tutor availability write" on tutor_availability for all using(tutor_id=auth.uid() or acme_role()='admin') with check(tutor_id=auth.uid() or acme_role()='admin');create policy "tutor blocks manage" on tutor_blocks for all using(tutor_id=auth.uid() or acme_role()='admin') with check(tutor_id=auth.uid() or acme_role()='admin');
create policy "own bookings" on coaching_bookings for select using(student_id=auth.uid() or tutor_id=auth.uid() or acme_role()='admin');
create policy "cohorts enrolled read" on cohorts for select using(true);create policy "staff cohorts write" on cohorts for all using(acme_role() in ('admin','tutor')) with check(acme_role() in ('admin','tutor'));
create policy "own waitlist" on waitlist_entries for select using(user_id=auth.uid() or acme_role()='admin');create policy "staff class changes" on class_changes for all using(acme_role() in ('admin','tutor')) with check(acme_role() in ('admin','tutor'));
create policy "published assessments" on assessment_versions for select using(status='published' or acme_role() in ('admin','tutor'));create policy "published questions" on question_items for select using(status='published' or acme_role() in ('admin','tutor'));create policy "staff questions" on question_items for all using(acme_role() in ('admin','tutor')) with check(acme_role() in ('admin','tutor'));
create policy "submission moderation" on marking_moderations for select using(acme_role() in ('admin','tutor') or exists(select 1 from writing_submissions s where s.id=submission_id and s.user_id=auth.uid()));
create policy "staff moderation write" on marking_moderations for all using(acme_role() in ('admin','tutor')) with check(acme_role() in ('admin','tutor'));create policy "own score review" on score_review_requests for all using(user_id=auth.uid() or acme_role() in ('admin','tutor')) with check(user_id=auth.uid() or acme_role() in ('admin','tutor'));
create policy "speaking comments write" on speaking_comments for insert with check(acme_role() in ('admin','tutor'));create policy "speaking comments access" on speaking_comments for select using(exists(select 1 from speaking_attempts a where a.id=attempt_id and (a.user_id=auth.uid() or acme_role() in ('admin','tutor'))));
create policy "own forecast" on readiness_forecasts for select using(user_id=auth.uid() or acme_role() in ('admin','tutor'));
create policy "active coupons read" on coupons for select using(active);create policy "admin coupons" on coupons for all using(acme_role()='admin') with check(acme_role()='admin');create policy "own scholarship" on scholarship_applications for all using(user_id=auth.uid() or acme_role()='admin') with check(user_id=auth.uid() or acme_role()='admin');
create policy "own invoice" on invoices for select using(exists(select 1 from orders o where o.id=order_id and (o.user_id=auth.uid() or acme_role()='admin')));create policy "own refunds" on refunds for select using(requested_by=auth.uid() or acme_role()='admin');create policy "own referrals" on referrals for select using(referrer_id=auth.uid() or acme_role()='admin');
create policy "staff incidents" on service_incidents for select using(acme_role() in ('admin','tutor'));create policy "admin incidents write" on service_incidents for all using(acme_role()='admin') with check(acme_role()='admin');
-- webhook jobs, dead letters and rate limits intentionally have no client policies.
create index booking_tutor_time on coaching_bookings(tutor_id,starts_at);create index waitlist_course on waitlist_entries(course_id,position);create index webhook_due on webhook_jobs(next_attempt_at) where status in ('queued','retry');
