(()=>{const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)],cloud=window.AcmeCloud;const note=m=>{const t=$('#toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}};
// Installable PWA
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});let installEvent;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;const b=$('#installBanner');if(b)b.style.display='flex'});$('#installApp')?.addEventListener('click',async()=>{await installEvent?.prompt();$('#installBanner').style.display='none'});
// Diagnostic assessment
$('#diagnosticForm')?.addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(e.currentTarget),answers={q1:'B',q2:'C',q3:'A',q4:'B'},correct=Object.entries(answers).filter(([k,v])=>d.get(k)===v).length,band=(5.5+correct*.5).toFixed(1),result=$('#diagnosticResult');result.innerHTML=`<span class="eyebrow">Practice-level indication</span><h2>Around Band ${band}</h2><p>This is not an official IELTS prediction. Your first plan prioritises writing structure and reading pace. Complete the speaking and writing samples for a four-skill estimate.</p><a class="btn btn-coral" href="${localStorage.getItem('acmeProfile')?'writing.html':'signup.html'}">${localStorage.getItem('acmeProfile')?'Continue to writing':'Save my result and continue'} →</a>`;result.classList.remove('hidden');localStorage.setItem('acmeDiagnostic',JSON.stringify({correct,band,completed:new Date()}));if(cloud&&!cloud.demoMode())try{const p=JSON.parse(localStorage.getItem('acmeProfile'));await fetch(`${ACME_CONFIG.SUPABASE_URL}/rest/v1/diagnostic_attempts`,{method:'POST',headers:{apikey:ACME_CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${cloud.session().access_token}`,'Content-Type':'application/json'},body:JSON.stringify({user_id:p.id,completed_at:new Date().toISOString(),responses:Object.fromEntries(d),scores:{reading:Number(band)}})});await cloud.invoke('generate-recommendations',{})}catch(err){note(err.message)}result.scrollIntoView({behavior:'smooth'})});
// Writing workspace: local autosave remains available offline.
const editor=$('#writingEditor');if(editor){const key='acmeWritingDraft';editor.value=localStorage.getItem(key)||'';const wc=$('#wordCount'),saved=$('#saveState');const update=()=>{wc.textContent=`${(editor.value.trim().match(/\S+/g)||[]).length} words`;localStorage.setItem(key,editor.value);saved.textContent='Saved locally · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})};editor.addEventListener('input',update);update();$('#submitWriting')?.addEventListener('click',async()=>{if((editor.value.match(/\S+/g)||[]).length<150)return note('Write at least 150 words before submitting.');if(cloud&&!cloud.demoMode())try{const p=JSON.parse(localStorage.getItem('acmeProfile'));await fetch(`${ACME_CONFIG.SUPABASE_URL}/rest/v1/writing_submissions`,{method:'POST',headers:{apikey:ACME_CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${cloud.session().access_token}`,'Content-Type':'application/json'},body:JSON.stringify({user_id:p.id,task_type:'task_2',question:$('#writingQuestion').textContent,response:editor.value,word_count:(editor.value.match(/\S+/g)||[]).length,status:'submitted',submitted_at:new Date().toISOString()})});note('Submitted to your tutor for rubric feedback.')}catch(e){note(e.message)}else note('Writing submitted in demo mode. Tutor feedback is now queued.')})}
// Shared countdowns
$$('[data-countdown]').forEach(el=>{let sec=Number(el.dataset.countdown);setInterval(()=>{if(sec<=0)return;sec--;el.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`},1000)});
// Speaking recorder
let recorder,chunks=[],stream;$('#recordSpeech')?.addEventListener('click',async e=>{try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=x=>chunks.push(x.data);recorder.onstop=()=>{const blob=new Blob(chunks,{type:'audio/webm'}),audio=$('#speechPlayback');window.acmeSpeechBlob=blob;audio.src=URL.createObjectURL(blob);audio.classList.remove('hidden');$('#speechStatus').textContent=`Recorded · ${Math.round(blob.size/1024)} KB · private until submitted`;stream.getTracks().forEach(t=>t.stop())};recorder.start();e.currentTarget.disabled=true;$('#stopSpeech').disabled=false;$('#speechStatus').textContent='Recording… Speak naturally.'}catch{note('Microphone permission is required.')}});$('#stopSpeech')?.addEventListener('click',e=>{recorder?.stop();e.currentTarget.disabled=true;$('#recordSpeech').disabled=false});$('#submitSpeech')?.addEventListener('click',async e=>{if(!window.acmeSpeechBlob)return note('Record and preview a response first.');const consent=e.currentTarget.parentElement.querySelector('input[type=checkbox]');if(!consent?.checked)return note('Recording consent is required before upload.');e.currentTarget.textContent='Uploading privately…';try{if(!cloud.demoMode()){const p=JSON.parse(localStorage.getItem('acmeProfile')),path=`${p.id}/${crypto.randomUUID()}.webm`,r=await fetch(`${ACME_CONFIG.SUPABASE_URL}/storage/v1/object/speaking-attempts/${path}`,{method:'POST',headers:{apikey:ACME_CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${cloud.session().access_token}`,'Content-Type':'audio/webm'},body:window.acmeSpeechBlob});if(!r.ok)throw Error((await r.json()).message||'Upload failed');await fetch(`${ACME_CONFIG.SUPABASE_URL}/rest/v1/speaking_attempts`,{method:'POST',headers:{apikey:ACME_CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${cloud.session().access_token}`,'Content-Type':'application/json'},body:JSON.stringify({user_id:p.id,part:2,question:'Describe a skill you would like to learn.',audio_path:path,status:'submitted'})})}note('Speaking response submitted privately to your tutor.')}catch(err){note(err.message)}finally{e.currentTarget.textContent='Submit to tutor →'}});
// Mock navigation
$$('.mock-option').forEach(o=>o.addEventListener('click',()=>{const p=$('.mock-option.active');p?.classList.remove('active');o.classList.add('active')}));$('#nextMock')?.addEventListener('click',()=>note('Response saved. Moving to the next question…'));
// Plan comparison
$('#compareForm')?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget),gap=Number(d.get('target'))-Number(d.get('current')),weeks=Number(d.get('weeks'));let plan='Practice Essentials',reason='Your longer timeline and smaller score gap make a self-paced route practical.';if(gap>=1||weeks<=8){plan='Complete Accelerator';reason='Your target-band gap and exam timeline benefit from structured live teaching and marked work.'}if(gap>=1.5||weeks<=2){plan='Pro Coaching';reason='Your short timeline or larger score gap needs personal tutor attention and rapid feedback.'}const out=$('#compareResult');out.innerHTML=`<strong>Recommended: ${plan}.</strong> ${reason} <a href="billing.html" style="float:right">View plan →</a>`;out.classList.remove('hidden')});
// Payments
$$('[data-product]').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;b.textContent='Opening secure checkout…';try{if(cloud.demoMode()){await new Promise(r=>setTimeout(r,500));note('Demo checkout ready. Add Paystack/Stripe keys for live payment.');b.disabled=false;b.textContent='Choose plan'}else{const out=await cloud.invoke('initialize-payment',{product_id:b.dataset.product,provider:b.dataset.provider||'paystack',coupon_code:$('#couponCode')?.value||null});window.AcmeOpenExternal?window.AcmeOpenExternal(out.checkout_url):location.href=out.checkout_url}}catch(e){note(e.message);b.disabled=false;b.textContent='Choose plan'}}));
// Notifications
$('#markAllRead')?.addEventListener('click',()=>{$$('.notice-item').forEach(n=>n.classList.remove('unread'));note('All notifications marked as read.')});
// Support
$('#supportForm')?.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));if(cloud&&!cloud.demoMode())try{const p=JSON.parse(localStorage.getItem('acmeProfile'));await fetch(`${ACME_CONFIG.SUPABASE_URL}/rest/v1/support_tickets`,{method:'POST',headers:{apikey:ACME_CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${cloud.session().access_token}`,'Content-Type':'application/json'},body:JSON.stringify({...d,user_id:p.id})});note('Ticket created. Support will reply by email.');e.currentTarget.reset()}catch(err){note(err.message)}else{note('Demo support ticket created.');e.currentTarget.reset()}});
// Product research
$('#researchForm')?.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),p=JSON.parse(localStorage.getItem('acmeProfile')||'null');d.rating=Number(d.rating);d.consent_followup=d.consent_followup==='on';d.user_id=p?.id||null;try{if(!cloud.demoMode())await fetch(`${ACME_CONFIG.SUPABASE_URL}/rest/v1/usability_feedback`,{method:'POST',headers:{apikey:ACME_CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${cloud.session()?.access_token||ACME_CONFIG.SUPABASE_ANON_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(d)});e.currentTarget.innerHTML='<span class="eyebrow">Thank you</span><h2>Your feedback was recorded.</h2><p>It will be reviewed with other journey results before the next product release.</p><a class="btn btn-dark" href="index.html">Return home</a>'}catch(err){note(err.message)}});
// Privacy export and deletion
$('#exportData')?.addEventListener('click',async()=>{try{const data=cloud.demoMode()?{profile:JSON.parse(localStorage.getItem('acmeProfile')),diagnostic:JSON.parse(localStorage.getItem('acmeDiagnostic')||'null'),writing:localStorage.getItem('acmeWritingDraft')}:await cloud.invoke('account-privacy',{action:'export'});const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='acmelearn-data-export.json';a.click()}catch(e){note(e.message)}});$('#deleteAccount')?.addEventListener('click',async()=>{const p=JSON.parse(localStorage.getItem('acmeProfile')||'{}'),email=prompt(`Type ${p.email||'your email'} to permanently delete your account:`);if(!email)return;try{if(!cloud.demoMode())await cloud.invoke('account-privacy',{action:'delete',confirm_email:email});await cloud.logout();location.href='index.html'}catch(e){note(e.message)}});
})();